### ISSUE TITLE
Remove margin below BeeLine button

### ISSUE THREAD

**Issue by onepopcorn** [iJaack/Jaack#30]
Just removing the class name "post" on [this line](https://github.com/iJaack/Jaack/blob/master/_layouts/post.html#L19) you'll prevent the margin below BeeLine's button.

**Comment by iJaack** [comment]
> Just removing the class name "post" on [this line](https://github.com/iJaack/Jaack/blob/master/_layouts/post.html#L19) you'll prevent the margin below BeeLine's button.

It worked, thank you!
